[package]
name = "say"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.9"
toml = "0.5"
uuid = {version="0.8",features=["v4"]}
serde = { version = "1", features = ["derive"] }
rodio = "0.14.0"
hound = "3.4.0"
# ureq = {version="2.4",features=["json","charset","native-certs"]}
ureq = {version="2.4",features=["json","charset","native-certs","tls"]}